// Code generated by impgen. DO NOT EDIT.

package targs

import (
	_imptest "github.com/toejough/imptest/imptest"
)

// MockrunEnv creates a new runEnvMock for testing.
func MockrunEnv(t _imptest.TestReporter) *runEnvMock {
	imp := _imptest.NewImp(t)
	return &runEnvMock{
		imp:     imp,
		Args:    _imptest.NewDependencyMethod(imp, "Args"),
		Printf:  &runEnvMockPrintfMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "Printf")},
		Println: &runEnvMockPrintlnMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "Println")},
		Exit:    &runEnvMockExitMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "Exit")},
	}
}

// mockrunEnvImpl implements runEnv.
type mockrunEnvImpl struct {
	mock *runEnvMock
}

// Args implements runEnv.Args.
func (impl *mockrunEnvImpl) Args() []string {
	call := &_imptest.GenericCall{
		MethodName:   "Args",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]string); ok {
			result1 = value
		}
	}

	return result1
}

// Exit implements runEnv.Exit.
func (impl *mockrunEnvImpl) Exit(code int) {
	call := &_imptest.GenericCall{
		MethodName:   "Exit",
		Args:         []any{code},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// Printf implements runEnv.Printf.
func (impl *mockrunEnvImpl) Printf(format string, args ...any) {
	callArgs := []any{format}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := &_imptest.GenericCall{
		MethodName:   "Printf",
		Args:         callArgs,
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// Println implements runEnv.Println.
func (impl *mockrunEnvImpl) Println(args ...any) {
	callArgs := []any{}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := &_imptest.GenericCall{
		MethodName:   "Println",
		Args:         callArgs,
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// runEnvMock is the mock for runEnv.
type runEnvMock struct {
	imp     *_imptest.Imp
	Args    *_imptest.DependencyMethod
	Printf  *runEnvMockPrintfMethod
	Println *runEnvMockPrintlnMethod
	Exit    *runEnvMockExitMethod
}

// Interface returns the runEnv implementation that can be passed to code under test.
func (m *runEnvMock) Interface() runEnv {
	return &mockrunEnvImpl{mock: m}
}

// runEnvMockArgsCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type runEnvMockArgsCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *runEnvMockArgsCall) InjectReturnValues(result0 []string) {
	c.DependencyCall.InjectReturnValues(result0)
}

// runEnvMockExitArgs holds typed arguments for Exit.
type runEnvMockExitArgs struct {
	Code int
}

// runEnvMockExitCall wraps DependencyCall with typed GetArgs.
type runEnvMockExitCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *runEnvMockExitCall) GetArgs() runEnvMockExitArgs {
	raw := c.RawArgs()
	return runEnvMockExitArgs{
		Code: raw[0].(int),
	}
}

// runEnvMockExitMethod wraps DependencyMethod with typed returns.
type runEnvMockExitMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *runEnvMockExitMethod) Eventually() *runEnvMockExitMethod {
	return &runEnvMockExitMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *runEnvMockExitMethod) ExpectCalledWithExactly(code int) *runEnvMockExitCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(code)
	return &runEnvMockExitCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *runEnvMockExitMethod) ExpectCalledWithMatches(matchers ...any) *runEnvMockExitCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &runEnvMockExitCall{DependencyCall: call}
}

// runEnvMockPrintfArgs holds typed arguments for Printf.
type runEnvMockPrintfArgs struct {
	Format string
	Args   []any
}

// runEnvMockPrintfCall wraps DependencyCall with typed GetArgs.
type runEnvMockPrintfCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *runEnvMockPrintfCall) GetArgs() runEnvMockPrintfArgs {
	raw := c.RawArgs()
	return runEnvMockPrintfArgs{
		Format: raw[0].(string),
		Args:   raw[1].([]any),
	}
}

// runEnvMockPrintfMethod wraps DependencyMethod with typed returns.
type runEnvMockPrintfMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *runEnvMockPrintfMethod) Eventually() *runEnvMockPrintfMethod {
	return &runEnvMockPrintfMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *runEnvMockPrintfMethod) ExpectCalledWithExactly(format string, args ...any) *runEnvMockPrintfCall {
	callArgs := []any{format}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := m.DependencyMethod.ExpectCalledWithExactly(callArgs...)
	return &runEnvMockPrintfCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *runEnvMockPrintfMethod) ExpectCalledWithMatches(matchers ...any) *runEnvMockPrintfCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &runEnvMockPrintfCall{DependencyCall: call}
}

// runEnvMockPrintlnArgs holds typed arguments for Println.
type runEnvMockPrintlnArgs struct {
	Args []any
}

// runEnvMockPrintlnCall wraps DependencyCall with typed GetArgs.
type runEnvMockPrintlnCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *runEnvMockPrintlnCall) GetArgs() runEnvMockPrintlnArgs {
	raw := c.RawArgs()
	return runEnvMockPrintlnArgs{
		Args: raw[0].([]any),
	}
}

// runEnvMockPrintlnMethod wraps DependencyMethod with typed returns.
type runEnvMockPrintlnMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *runEnvMockPrintlnMethod) Eventually() *runEnvMockPrintlnMethod {
	return &runEnvMockPrintlnMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *runEnvMockPrintlnMethod) ExpectCalledWithExactly(args ...any) *runEnvMockPrintlnCall {
	callArgs := []any{}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := m.DependencyMethod.ExpectCalledWithExactly(callArgs...)
	return &runEnvMockPrintlnCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *runEnvMockPrintlnMethod) ExpectCalledWithMatches(matchers ...any) *runEnvMockPrintlnCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &runEnvMockPrintlnCall{DependencyCall: call}
}
