// Code generated by impgen. DO NOT EDIT.

package buildtool

import (
	_imptest "github.com/toejough/imptest/imptest"
	fs "io/fs"
)

// FileSystemMock is the mock for FileSystem.
type FileSystemMock struct {
	imp       *_imptest.Imp
	ReadDir   *FileSystemMockReadDirMethod
	ReadFile  *FileSystemMockReadFileMethod
	WriteFile *FileSystemMockWriteFileMethod
}

// Interface returns the FileSystem implementation that can be passed to code under test.
func (m *FileSystemMock) Interface() FileSystem {
	return &mockFileSystemImpl{mock: m}
}

// FileSystemMockReadDirArgs holds typed arguments for ReadDir.
type FileSystemMockReadDirArgs struct {
	Name string
}

// FileSystemMockReadDirCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileSystemMockReadDirCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *FileSystemMockReadDirCall) GetArgs() FileSystemMockReadDirArgs {
	raw := c.RawArgs()
	return FileSystemMockReadDirArgs{
		Name: raw[0].(string),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileSystemMockReadDirCall) InjectReturnValues(result0 []fs.DirEntry, result1 error) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// FileSystemMockReadDirMethod wraps DependencyMethod with typed returns.
type FileSystemMockReadDirMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *FileSystemMockReadDirMethod) Eventually() *FileSystemMockReadDirMethod {
	return &FileSystemMockReadDirMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *FileSystemMockReadDirMethod) ExpectCalledWithExactly(name string) *FileSystemMockReadDirCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(name)
	return &FileSystemMockReadDirCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *FileSystemMockReadDirMethod) ExpectCalledWithMatches(matchers ...any) *FileSystemMockReadDirCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &FileSystemMockReadDirCall{DependencyCall: call}
}

// FileSystemMockReadFileArgs holds typed arguments for ReadFile.
type FileSystemMockReadFileArgs struct {
	Name string
}

// FileSystemMockReadFileCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileSystemMockReadFileCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *FileSystemMockReadFileCall) GetArgs() FileSystemMockReadFileArgs {
	raw := c.RawArgs()
	return FileSystemMockReadFileArgs{
		Name: raw[0].(string),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileSystemMockReadFileCall) InjectReturnValues(result0 []byte, result1 error) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// FileSystemMockReadFileMethod wraps DependencyMethod with typed returns.
type FileSystemMockReadFileMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *FileSystemMockReadFileMethod) Eventually() *FileSystemMockReadFileMethod {
	return &FileSystemMockReadFileMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *FileSystemMockReadFileMethod) ExpectCalledWithExactly(name string) *FileSystemMockReadFileCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(name)
	return &FileSystemMockReadFileCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *FileSystemMockReadFileMethod) ExpectCalledWithMatches(matchers ...any) *FileSystemMockReadFileCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &FileSystemMockReadFileCall{DependencyCall: call}
}

// FileSystemMockWriteFileArgs holds typed arguments for WriteFile.
type FileSystemMockWriteFileArgs struct {
	Name string
	Data []byte
	Perm fs.FileMode
}

// FileSystemMockWriteFileCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileSystemMockWriteFileCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *FileSystemMockWriteFileCall) GetArgs() FileSystemMockWriteFileArgs {
	raw := c.RawArgs()
	return FileSystemMockWriteFileArgs{
		Name: raw[0].(string),
		Data: raw[1].([]byte),
		Perm: raw[2].(fs.FileMode),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileSystemMockWriteFileCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// FileSystemMockWriteFileMethod wraps DependencyMethod with typed returns.
type FileSystemMockWriteFileMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *FileSystemMockWriteFileMethod) Eventually() *FileSystemMockWriteFileMethod {
	return &FileSystemMockWriteFileMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *FileSystemMockWriteFileMethod) ExpectCalledWithExactly(name string, data []byte, perm fs.FileMode) *FileSystemMockWriteFileCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(name, data, perm)
	return &FileSystemMockWriteFileCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *FileSystemMockWriteFileMethod) ExpectCalledWithMatches(matchers ...any) *FileSystemMockWriteFileCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &FileSystemMockWriteFileCall{DependencyCall: call}
}

// MockFileSystem creates a new FileSystemMock for testing.
func MockFileSystem(t _imptest.TestReporter) *FileSystemMock {
	imp := _imptest.NewImp(t)
	return &FileSystemMock{
		imp:       imp,
		ReadDir:   &FileSystemMockReadDirMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "ReadDir")},
		ReadFile:  &FileSystemMockReadFileMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "ReadFile")},
		WriteFile: &FileSystemMockWriteFileMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "WriteFile")},
	}
}

// mockFileSystemImpl implements FileSystem.
type mockFileSystemImpl struct {
	mock *FileSystemMock
}

// ReadDir implements FileSystem.ReadDir.
func (impl *mockFileSystemImpl) ReadDir(name string) ([]fs.DirEntry, error) {
	call := &_imptest.GenericCall{
		MethodName:   "ReadDir",
		Args:         []any{name},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []fs.DirEntry
	var result2 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]fs.DirEntry); ok {
			result1 = value
		}
	}
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// ReadFile implements FileSystem.ReadFile.
func (impl *mockFileSystemImpl) ReadFile(name string) ([]byte, error) {
	call := &_imptest.GenericCall{
		MethodName:   "ReadFile",
		Args:         []any{name},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []byte
	var result2 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]byte); ok {
			result1 = value
		}
	}
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// WriteFile implements FileSystem.WriteFile.
func (impl *mockFileSystemImpl) WriteFile(name string, data []byte, perm fs.FileMode) error {
	call := &_imptest.GenericCall{
		MethodName:   "WriteFile",
		Args:         []any{name, data, perm},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}
