package buildtool

import (
	"io/fs"
	"testing"
)

func TestGenerateFunctionWrappers_BuildTagAndDescriptions(t *testing.T) {
	fsMock := MockFileSystem(t)
	done := make(chan struct{})
	var (
		path string
		err  error
	)

	go func() {
		path, err = GenerateFunctionWrappers(fsMock.Mock, GenerateOptions{
			Dir:        "/root",
			BuildTag:   "targ",
			OnlyTagged: true,
		})
		close(done)
	}()

	fsMock.Method.ReadDir.ExpectCalledWithExactly("/root").InjectReturnValues([]fs.DirEntry{
		fakeDirEntry{name: "cmd.go", dir: false},
		fakeDirEntry{name: "other.go", dir: false},
	}, nil)
	fsMock.Method.ReadFile.ExpectCalledWithExactly("/root/cmd.go").
		InjectReturnValues([]byte(`//go:build targ

package build

// Build does work.
func Build() {}

// Deploy does more.
func Deploy() error { return nil }
`), nil)
	fsMock.Method.ReadFile.ExpectCalledWithExactly("/root/other.go").
		InjectReturnValues([]byte(`package other

func Ignored() {}
`), nil)

	expected := `//go:build targ

// Code generated by targ. DO NOT EDIT.

package build

type BuildCommand struct{}

func (c *BuildCommand) Run() {
	Build()
}

func (c *BuildCommand) Name() string {
	return "Build"
}

func (c *BuildCommand) Description() string {
	return "Build does work."
}

type DeployCommand struct{}

func (c *DeployCommand) Run() error {
	return Deploy()
}

func (c *DeployCommand) Name() string {
	return "Deploy"
}

func (c *DeployCommand) Description() string {
	return "Deploy does more."
}
`

	fsMock.Method.WriteFile.ExpectCalledWithExactly(
		"/root/generated_targ_build.go",
		[]byte(expected),
		fs.FileMode(0o644),
	).InjectReturnValues(nil)

	<-done

	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if path != "/root/generated_targ_build.go" {
		t.Fatalf("expected generated file path, got %q", path)
	}
}

func TestGenerateFunctionWrappers_ContextRun(t *testing.T) {
	fsMock := MockFileSystem(t)
	done := make(chan struct{})
	var (
		path string
		err  error
	)

	go func() {
		path, err = GenerateFunctionWrappers(fsMock.Mock, GenerateOptions{
			Dir:        "/root",
			BuildTag:   "targ",
			OnlyTagged: true,
		})
		close(done)
	}()

	fsMock.Method.ReadDir.ExpectCalledWithExactly("/root").InjectReturnValues([]fs.DirEntry{
		fakeDirEntry{name: "cmd.go", dir: false},
	}, nil)
	fsMock.Method.ReadFile.ExpectCalledWithExactly("/root/cmd.go").
		InjectReturnValues([]byte(`//go:build targ

package build

import "context"

// Run it.
func Run(ctx context.Context) {}
`), nil)

	expected := `//go:build targ

// Code generated by targ. DO NOT EDIT.

package build

import "context"

type RunCommand struct{}

func (c *RunCommand) Run(ctx context.Context) {
	Run(ctx)
}

func (c *RunCommand) Name() string {
	return "Run"
}

func (c *RunCommand) Description() string {
	return "Run it."
}
`

	fsMock.Method.WriteFile.ExpectCalledWithExactly(
		"/root/generated_targ_build.go",
		[]byte(expected),
		fs.FileMode(0o644),
	).InjectReturnValues(nil)

	<-done

	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if path != "/root/generated_targ_build.go" {
		t.Fatalf("expected generated file path, got %q", path)
	}
}

func TestGenerateFunctionWrappers_ErrorsOnNameCollision(t *testing.T) {
	fsMock := MockFileSystem(t)
	done := make(chan struct{})
	var err error

	go func() {
		_, err = GenerateFunctionWrappers(fsMock.Mock, GenerateOptions{
			Dir:        "/root",
			BuildTag:   "targ",
			OnlyTagged: true,
		})
		close(done)
	}()

	fsMock.Method.ReadDir.ExpectCalledWithExactly("/root").InjectReturnValues([]fs.DirEntry{
		fakeDirEntry{name: "cmd.go", dir: false},
	}, nil)
	fsMock.Method.ReadFile.ExpectCalledWithExactly("/root/cmd.go").
		InjectReturnValues([]byte(`//go:build targ

package build

type BuildCommand struct{}

func Build() {}
`), nil)

	<-done

	if err == nil {
		t.Fatal("expected name collision error")
	}
}

func TestGenerateFunctionWrappers_SkipsSubcommandFunctions(t *testing.T) {
	fsMock := MockFileSystem(t)
	done := make(chan struct{})
	var (
		path string
		err  error
	)

	go func() {
		path, err = GenerateFunctionWrappers(fsMock.Mock, GenerateOptions{
			Dir:        "/root",
			BuildTag:   "targ",
			OnlyTagged: true,
		})
		close(done)
	}()

	fsMock.Method.ReadDir.ExpectCalledWithExactly("/root").InjectReturnValues([]fs.DirEntry{
		fakeDirEntry{name: "cmd.go", dir: false},
	}, nil)
	fsMock.Method.ReadFile.ExpectCalledWithExactly("/root/cmd.go").
		InjectReturnValues([]byte(`//go:build targ

package build

type Root struct {
	Build func() `+"`targ:\"subcommand\"`"+`
}

func Build() {}
`), nil)

	<-done

	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if path != "" {
		t.Fatalf("expected no generated file, got %q", path)
	}
}
