// Code generated by impgen. DO NOT EDIT.
// impgen:hash:7c0acbb164338f9f

package discover

import (
	_imptest "github.com/toejough/imptest"
	fs "io/fs"
)

type FileSystemImp struct {
	ReadDir   *FileSystemMockReadDirMethod
	ReadFile  *FileSystemMockReadFileMethod
	WriteFile *FileSystemMockWriteFileMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *FileSystemImpEventually
}

type FileSystemImpEventually struct {
	ReadDir   *FileSystemMockReadDirMethod
	ReadFile  *FileSystemMockReadFileMethod
	WriteFile *FileSystemMockWriteFileMethod
}

type FileSystemMockReadDirArgs struct {
	Name string
}

type FileSystemMockReadDirCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *FileSystemMockReadDirCall) GetArgs() FileSystemMockReadDirArgs {
	raw := c.RawArgs()
	return FileSystemMockReadDirArgs{
		Name: raw[0].(string),
	}
}

// Return specifies the typed values the mock should return.
func (c *FileSystemMockReadDirCall) Return(result0 []fs.DirEntry, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type FileSystemMockReadDirMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *FileSystemMockReadDirMethod) ArgsEqual(name string) *FileSystemMockReadDirCall {
	call := m.DependencyMethod.ArgsEqual(name)
	return &FileSystemMockReadDirCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *FileSystemMockReadDirMethod) ArgsShould(matchers ...any) *FileSystemMockReadDirCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &FileSystemMockReadDirCall{DependencyCall: call}
}

type FileSystemMockReadFileArgs struct {
	Name string
}

type FileSystemMockReadFileCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *FileSystemMockReadFileCall) GetArgs() FileSystemMockReadFileArgs {
	raw := c.RawArgs()
	return FileSystemMockReadFileArgs{
		Name: raw[0].(string),
	}
}

// Return specifies the typed values the mock should return.
func (c *FileSystemMockReadFileCall) Return(result0 []byte, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type FileSystemMockReadFileMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *FileSystemMockReadFileMethod) ArgsEqual(name string) *FileSystemMockReadFileCall {
	call := m.DependencyMethod.ArgsEqual(name)
	return &FileSystemMockReadFileCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *FileSystemMockReadFileMethod) ArgsShould(matchers ...any) *FileSystemMockReadFileCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &FileSystemMockReadFileCall{DependencyCall: call}
}

type FileSystemMockWriteFileArgs struct {
	Name string
	Data []byte
	Perm fs.FileMode
}

type FileSystemMockWriteFileCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *FileSystemMockWriteFileCall) GetArgs() FileSystemMockWriteFileArgs {
	raw := c.RawArgs()
	return FileSystemMockWriteFileArgs{
		Name: raw[0].(string),
		Data: raw[1].([]byte),
		Perm: raw[2].(fs.FileMode),
	}
}

// Return specifies the typed values the mock should return.
func (c *FileSystemMockWriteFileCall) Return(result0 error) {
	c.DependencyCall.Return(result0)
}

type FileSystemMockWriteFileMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *FileSystemMockWriteFileMethod) ArgsEqual(name string, data []byte, perm fs.FileMode) *FileSystemMockWriteFileCall {
	call := m.DependencyMethod.ArgsEqual(name, data, perm)
	return &FileSystemMockWriteFileCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *FileSystemMockWriteFileMethod) ArgsShould(matchers ...any) *FileSystemMockWriteFileCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &FileSystemMockWriteFileCall{DependencyCall: call}
}

// MockFileSystem creates a mock FileSystem and returns (mock, expectation handle).
func MockFileSystem(t _imptest.TestReporter) (FileSystem, *FileSystemImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &FileSystemImp{
		ReadDir:   newFileSystemMockReadDirMethod(_imptest.NewDependencyMethod(ctrl, "ReadDir")),
		ReadFile:  newFileSystemMockReadFileMethod(_imptest.NewDependencyMethod(ctrl, "ReadFile")),
		WriteFile: newFileSystemMockWriteFileMethod(_imptest.NewDependencyMethod(ctrl, "WriteFile")),
	}
	imp.Eventually = &FileSystemImpEventually{
		ReadDir:   newFileSystemMockReadDirMethod(_imptest.NewDependencyMethod(ctrl, "ReadDir").AsEventually()),
		ReadFile:  newFileSystemMockReadFileMethod(_imptest.NewDependencyMethod(ctrl, "ReadFile").AsEventually()),
		WriteFile: newFileSystemMockWriteFileMethod(_imptest.NewDependencyMethod(ctrl, "WriteFile").AsEventually()),
	}
	mock := &mockFileSystemImpl{ctrl: ctrl}
	return mock, imp
}

type mockFileSystemImpl struct {
	ctrl *_imptest.Imp
}

// ReadDir implements FileSystem.ReadDir.
func (impl *mockFileSystemImpl) ReadDir(name string) ([]fs.DirEntry, error) {
	call := &_imptest.GenericCall{
		MethodName:   "ReadDir",
		Args:         []any{name},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []fs.DirEntry
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]fs.DirEntry); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// ReadFile implements FileSystem.ReadFile.
func (impl *mockFileSystemImpl) ReadFile(name string) ([]byte, error) {
	call := &_imptest.GenericCall{
		MethodName:   "ReadFile",
		Args:         []any{name},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []byte
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]byte); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// WriteFile implements FileSystem.WriteFile.
func (impl *mockFileSystemImpl) WriteFile(name string, data []byte, perm fs.FileMode) error {
	call := &_imptest.GenericCall{
		MethodName:   "WriteFile",
		Args:         []any{name, data, perm},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// newFileSystemMockReadDirMethod creates a typed method wrapper.
func newFileSystemMockReadDirMethod(dm *_imptest.DependencyMethod) *FileSystemMockReadDirMethod {
	return &FileSystemMockReadDirMethod{DependencyMethod: dm}
}

// newFileSystemMockReadFileMethod creates a typed method wrapper.
func newFileSystemMockReadFileMethod(dm *_imptest.DependencyMethod) *FileSystemMockReadFileMethod {
	return &FileSystemMockReadFileMethod{DependencyMethod: dm}
}

// newFileSystemMockWriteFileMethod creates a typed method wrapper.
func newFileSystemMockWriteFileMethod(dm *_imptest.DependencyMethod) *FileSystemMockWriteFileMethod {
	return &FileSystemMockWriteFileMethod{DependencyMethod: dm}
}
