// Code generated by impgen. DO NOT EDIT.

package core

import (
	_imptest "github.com/toejough/imptest"
)

// MockrunEnv creates a new runEnvMockHandle for testing.
func MockrunEnv(t _imptest.TestReporter) *runEnvMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &runEnvMockMethods{
		Args:    _imptest.NewDependencyMethod(ctrl, "Args"),
		Printf:  newrunEnvMockPrintfMethod(_imptest.NewDependencyMethod(ctrl, "Printf")),
		Println: newrunEnvMockPrintlnMethod(_imptest.NewDependencyMethod(ctrl, "Println")),
		Exit:    newrunEnvMockExitMethod(_imptest.NewDependencyMethod(ctrl, "Exit")),
	}
	h := &runEnvMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockrunEnvImpl{handle: h}
	return h
}

// mockrunEnvImpl implements runEnv.
type mockrunEnvImpl struct {
	handle *runEnvMockHandle
}

// Args implements runEnv.Args.
func (impl *mockrunEnvImpl) Args() []string {
	call := &_imptest.GenericCall{
		MethodName:   "Args",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]string); ok {
			result1 = value
		}
	}

	return result1
}

// Exit implements runEnv.Exit.
func (impl *mockrunEnvImpl) Exit(code int) {
	call := &_imptest.GenericCall{
		MethodName:   "Exit",
		Args:         []any{code},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// Printf implements runEnv.Printf.
func (impl *mockrunEnvImpl) Printf(format string, args ...any) {
	callArgs := []any{format}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := &_imptest.GenericCall{
		MethodName:   "Printf",
		Args:         callArgs,
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// Println implements runEnv.Println.
func (impl *mockrunEnvImpl) Println(args ...any) {
	callArgs := []any{}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := &_imptest.GenericCall{
		MethodName:   "Println",
		Args:         callArgs,
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// runEnvMockArgsCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type runEnvMockArgsCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *runEnvMockArgsCall) InjectReturnValues(result0 []string) {
	c.DependencyCall.InjectReturnValues(result0)
}

// runEnvMockExitArgs holds typed arguments for Exit.
type runEnvMockExitArgs struct {
	Code int
}

// runEnvMockExitCall wraps DependencyCall with typed GetArgs.
type runEnvMockExitCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *runEnvMockExitCall) GetArgs() runEnvMockExitArgs {
	raw := c.RawArgs()
	return runEnvMockExitArgs{
		Code: raw[0].(int),
	}
}

// runEnvMockExitMethod wraps DependencyMethod with typed returns.
type runEnvMockExitMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *runEnvMockExitMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *runEnvMockExitMethod) ExpectCalledWithExactly(code int) *runEnvMockExitCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(code)
	return &runEnvMockExitCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *runEnvMockExitMethod) ExpectCalledWithMatches(matchers ...any) *runEnvMockExitCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &runEnvMockExitCall{DependencyCall: call}
}

// runEnvMockHandle is the test handle for runEnv.
type runEnvMockHandle struct {
	Mock       runEnv
	Method     *runEnvMockMethods
	Controller *_imptest.Imp
}

// runEnvMockMethods holds method wrappers for setting expectations.
type runEnvMockMethods struct {
	Args    *_imptest.DependencyMethod
	Printf  *runEnvMockPrintfMethod
	Println *runEnvMockPrintlnMethod
	Exit    *runEnvMockExitMethod
}

// runEnvMockPrintfArgs holds typed arguments for Printf.
type runEnvMockPrintfArgs struct {
	Format string
	Args   []any
}

// runEnvMockPrintfCall wraps DependencyCall with typed GetArgs.
type runEnvMockPrintfCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *runEnvMockPrintfCall) GetArgs() runEnvMockPrintfArgs {
	raw := c.RawArgs()
	return runEnvMockPrintfArgs{
		Format: raw[0].(string),
		Args:   raw[1].([]any),
	}
}

// runEnvMockPrintfMethod wraps DependencyMethod with typed returns.
type runEnvMockPrintfMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *runEnvMockPrintfMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *runEnvMockPrintfMethod) ExpectCalledWithExactly(format string, args ...any) *runEnvMockPrintfCall {
	callArgs := []any{format}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := m.DependencyMethod.ExpectCalledWithExactly(callArgs...)
	return &runEnvMockPrintfCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *runEnvMockPrintfMethod) ExpectCalledWithMatches(matchers ...any) *runEnvMockPrintfCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &runEnvMockPrintfCall{DependencyCall: call}
}

// runEnvMockPrintlnArgs holds typed arguments for Println.
type runEnvMockPrintlnArgs struct {
	Args []any
}

// runEnvMockPrintlnCall wraps DependencyCall with typed GetArgs.
type runEnvMockPrintlnCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *runEnvMockPrintlnCall) GetArgs() runEnvMockPrintlnArgs {
	raw := c.RawArgs()
	return runEnvMockPrintlnArgs{
		Args: raw[0].([]any),
	}
}

// runEnvMockPrintlnMethod wraps DependencyMethod with typed returns.
type runEnvMockPrintlnMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *runEnvMockPrintlnMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *runEnvMockPrintlnMethod) ExpectCalledWithExactly(args ...any) *runEnvMockPrintlnCall {
	callArgs := []any{}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := m.DependencyMethod.ExpectCalledWithExactly(callArgs...)
	return &runEnvMockPrintlnCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *runEnvMockPrintlnMethod) ExpectCalledWithMatches(matchers ...any) *runEnvMockPrintlnCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &runEnvMockPrintlnCall{DependencyCall: call}
}

// newrunEnvMockExitMethod creates a typed method wrapper with Eventually initialized.
func newrunEnvMockExitMethod(dm *_imptest.DependencyMethod) *runEnvMockExitMethod {
	m := &runEnvMockExitMethod{DependencyMethod: dm}
	m.Eventually = &runEnvMockExitMethod{DependencyMethod: dm.Eventually}
	return m
}

// newrunEnvMockPrintfMethod creates a typed method wrapper with Eventually initialized.
func newrunEnvMockPrintfMethod(dm *_imptest.DependencyMethod) *runEnvMockPrintfMethod {
	m := &runEnvMockPrintfMethod{DependencyMethod: dm}
	m.Eventually = &runEnvMockPrintfMethod{DependencyMethod: dm.Eventually}
	return m
}

// newrunEnvMockPrintlnMethod creates a typed method wrapper with Eventually initialized.
func newrunEnvMockPrintlnMethod(dm *_imptest.DependencyMethod) *runEnvMockPrintlnMethod {
	m := &runEnvMockPrintlnMethod{DependencyMethod: dm}
	m.Eventually = &runEnvMockPrintlnMethod{DependencyMethod: dm.Eventually}
	return m
}
