// TEST-022: Help generators properties - validates root help with deregistered packages
// traces: ARCH-007, ARCH-003

package help_test

import (
	"bytes"
	"strings"
	"testing"

	. "github.com/onsi/gomega"
	"pgregory.net/rapid"

	"github.com/toejough/targ/internal/help"
)

func TestProperty_WriteRootHelpWithDeregisteredPackages(t *testing.T) {
	t.Parallel()

	rapid.Check(t, func(t *rapid.T) {
		g := NewWithT(t)

		count := rapid.IntRange(1, 4).Draw(t, "count")

		pkgs := make([]string, 0, count)
		for range count {
			pkg := rapid.StringMatching(`[a-z]+\.[a-z]+/[a-z0-9-]+/[a-z0-9-]+`).Draw(t, "pkg")
			pkgs = append(pkgs, pkg)
		}

		var buf strings.Builder
		help.WriteRootHelp(&buf, help.RootHelpOpts{
			BinaryName:           "targ",
			Description:          "Test description",
			DeregisteredPackages: pkgs,
		})
		output := buf.String()

		g.Expect(output).To(ContainSubstring("Deregistered packages"))

		for _, pkg := range pkgs {
			g.Expect(output).To(ContainSubstring(pkg))
		}
	})
}

func TestAutoGeneratedRootExamples(t *testing.T) {
	t.Parallel()

	t.Run("TargModeRootExamples", func(t *testing.T) {
		g := NewWithT(t)
		var buf bytes.Buffer

		opts := help.RootHelpOpts{
			BinaryName:  "targ",
			Description: "Build tool",
			CommandGroups: []help.CommandGroup{
				{Source: "dev/", Commands: []help.Command{
					{Name: "build", Desc: "Build the project"},
					{Name: "test", Desc: "Run tests"},
				}},
			},
			Filter: help.TargFlagFilter{IsRoot: true},
		}

		help.WriteRootHelp(&buf, opts)
		output := buf.String()

		// Should have auto-generated examples using actual command names
		g.Expect(output).To(ContainSubstring("targ build"))
		g.Expect(output).To(ContainSubstring("targ build test"))
	})

	t.Run("BinaryModeRootExamples", func(t *testing.T) {
		g := NewWithT(t)
		var buf bytes.Buffer

		opts := help.RootHelpOpts{
			BinaryName:  "myapp",
			Description: "My app",
			CommandGroups: []help.CommandGroup{
				{Source: "main.go", Commands: []help.Command{
					{Name: "greet", Desc: "Say hello"},
				}},
			},
			Filter: help.TargFlagFilter{IsRoot: true, BinaryMode: true},
		}

		help.WriteRootHelp(&buf, opts)
		output := buf.String()

		// Should use binary name
		g.Expect(output).To(ContainSubstring("myapp greet"))
		// Should NOT reference "targ"
		g.Expect(output).ToNot(ContainSubstring("targ"))
	})

	t.Run("UserExamplesReplace", func(t *testing.T) {
		g := NewWithT(t)
		var buf bytes.Buffer

		opts := help.RootHelpOpts{
			BinaryName:  "targ",
			Description: "Build tool",
			Examples: []help.Example{
				{Title: "Custom", Code: "targ custom-thing"},
			},
			Filter: help.TargFlagFilter{IsRoot: true},
		}

		help.WriteRootHelp(&buf, opts)
		output := buf.String()

		// User examples should replace auto-generated ones
		g.Expect(output).To(ContainSubstring("targ custom-thing"))
	})
}
